<?php
/**
 * Initialize the custom Settings.
 *
 * @package Prince
 */

add_action( 'init', 'custom_settings' );

/**
 * Build the custom settings & update Prince.
 *
 * @since     1.0.0
 */
function custom_settings() {

	// Prince is not loaded yet, or this is not an admin request.
	if ( ! function_exists( 'prince_settings_id' ) || ! is_admin() ) {
		return false;
	}

	/**
	 * Get a copy of the saved settings array.
	 */
	$saved_settings = get_option( prince_settings_id(), array() );

	/**
	 * Custom settings array that will eventually be
	 * passes to the Prince Settings API Class.
	 */
	$custom_settings = array(
		'contextual_help' => array(
			'content' => array(
				array(
					'id'      => 'option_types_help',
					'title'   => __( 'Option Types', 'notification-plus' ),
					'content' => '<p>' . __( 'Help content goes here!', 'notification-plus' ) . '</p>',
				),
			),
			'sidebar' => '<p>' . __( 'Sidebar content goes here!', 'notification-plus' ) . '</p>',
		),
		'sections'        => array(
			array(
				'id'    => 'option_types',
				'title' => __( 'Option Types', 'notification-plus' ),
			),
		),
		'settings'        => array(
			array(
				'id'           => 'demo_background',
				'label'        => __( 'Background', 'notification-plus' ),
				'desc'         => sprintf( __( 'The Background option type is for adding background styles to your theme either dynamically via the CSS option type below or manually with %1$s. The Background option type has filters that allow you to remove fields or change the defaults. For example, you can filter %2$s to remove unwanted fields from all Background options or an individual one. You can also filter %3$s. These filters allow you to fine tune the select lists for your specific needs.', 'notification-plus' ), '<code>prince_get_option()</code>', '<code>prince_recognized_background_fields</code>', '<code>prince_recognized_background_repeat</code>, <code>prince_recognized_background_attachment</code>, <code>prince_recognized_background_position</code>, ' . __( 'and', 'notification-plus' ) . ' <code>prince_type_background_size_choices</code>' ),
				'std'          => '',
				'type'         => 'background',
				'section'      => 'option_types',
				'block'        => true,
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_border',
				'label'        => __( 'Border', 'notification-plus' ),
				'desc'         => __( 'The Border option type is used to set width, unit, style, and color values.', 'notification-plus' ),
				'std'          => '',
				'block'        => true,
				'type'         => 'border',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_box_shadow',
				'label'        => __( 'Box Shadow', 'notification-plus' ),
				'desc'         => sprintf( __( 'The Box Shadow option type is used to set %1$s, %2$s, %3$s, %4$s, %5$s, and %6$s values.', 'notification-plus' ), '<code>inset</code>', '<code>offset-x</code>', '<code>offset-y</code>', '<code>blur-radius</code>', '<code>spread-radius</code>', '<code>color</code>' ),
				'std'          => '',
				'type'         => 'box-shadow',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_category_checkbox',
				'label'        => __( 'Category Checkbox', 'notification-plus' ),
				'desc'         => __( 'The Category Checkbox option type displays a list of category IDs. It allows the user to check multiple category IDs and will return that value as an array for use in a custom function or loop.', 'notification-plus' ),
				'std'          => '',
				'type'         => 'category-checkbox',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_category_select',
				'label'        => __( 'Category Select', 'notification-plus' ),
				'desc'         => __( 'The Category Select option type displays a list of category IDs. It allows the user to select only one category ID and will return that value for use in a custom function or loop.', 'notification-plus' ),
				'std'          => '',
				'type'         => 'category-select',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_checkbox',
				'label'        => __( 'Checkbox', 'notification-plus' ),
				'desc'         => __( 'The Checkbox option type displays a group of choices. It allows the user to check multiple choices and will return that value as an array for use in a custom function or loop.', 'notification-plus' ),
				'std'          => '',
				'type'         => 'checkbox',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
				'choices'      => array(
					array(
						'value' => 'no',
						'label' => __( 'No', 'notification-plus' ),
						'src'   => '',
					),
					array(
						'value' => 'Yes',
						'label' => __( 'Yes', 'notification-plus' ),
						'src'   => '',
					),
				),
			),
			array(
				'id'           => 'demo_colorpicker',
				'label'        => __( 'Colorpicker', 'notification-plus' ),
				'desc'         => __( 'The Colorpicker option type saves a hexadecimal color code for use in CSS. Use it to modify the color of something in your theme.', 'notification-plus' ),
				'std'          => '',
				'type'         => 'colorpicker',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_colorpicker_opacity',
				'label'        => __( 'Colorpicker Opacity', 'notification-plus' ),
				'desc'         => __( 'Colorpicker Opacity', 'notification-plus' ),
				'desc'         => sprintf( __( 'The Colorpicker Opacity option type saves an rgba color value for use in CSS. To add opacity to other colorpickers add the %1$s class to the %2$s array.', 'notification-plus' ), '<code>prince-colorpicker-opacity</code>', '<code>$args</code>' ),
				'std'          => '',
				'type'         => 'colorpicker-opacity',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_css',
				'label'        => __( 'CSS', 'notification-plus' ),
				'desc'         => '<p>' . sprintf( __( 'The CSS option type is a textarea that when used properly can add dynamic CSS to your theme from within Prince. Unfortunately, due server limitations you will need to create a file named %1$s at the root level of your theme and change permissions using %2$s so the server can write to the file. I have had the most success setting this single file to %3$s but feel free to play around with permissions until everything is working. A good starting point is %4$s. When the server can save to the file, CSS will automatically be updated when you save your Settings.', 'notification-plus' ), '<code>dynamic.css</code>', '<code>chmod</code>', '<code>0777</code>', '<code>0666</code>' ) . '</p><p>' . sprintf( __( 'This example assumes you have an option with the ID of %1$s. Which means this option will automatically insert the value of %1$s into the %2$s when the Settings are saved.', 'notification-plus' ), '<code>demo_background</code>', '<code>dynamic.css</code>' ) . '</p>',
				'std'          => '#custom {
  {{demo_background}}
}',
				'type'         => 'css',
				'section'      => 'option_types',
				'rows'         => '20',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_custom_post_type_checkbox',
				'label'        => __( 'Custom Post Type Checkbox', 'notification-plus' ),
				'desc'         => sprintf( __( 'The Custom Post Type Select option type displays a list of IDs from any available WordPress post type or custom post type. It allows the user to check multiple post IDs for use in a custom function or loop. Requires at least one valid %1$s in the %1$s field.', 'notification-plus' ), '<code>post_type</code>' ),
				'std'          => '',
				'type'         => 'custom-post-type-checkbox',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => 'post',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_custom_post_type_select',
				'label'        => __( 'Custom Post Type Select', 'notification-plus' ),
				'desc'         => sprintf( __( 'The Custom Post Type Select option type displays a list of IDs from any available WordPress post type or custom post type. It will return a single post ID for use in a custom function or loop. Requires at least one valid %1$s in the %1$s field.', 'notification-plus' ), '<code>post_type</code>' ),
				'std'          => '',
				'type'         => 'custom-post-type-select',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => 'post',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_date_picker',
				'label'        => __( 'Date Picker', 'notification-plus' ),
				'desc'         => __( 'The Date Picker option type is tied to a standard form input field which displays a calendar pop-up that allow the user to pick any date when focus is given to the input field. The returned value is a date formatted string.', 'notification-plus' ),
				'std'          => '',
				'type'         => 'date-picker',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_date_time_picker',
				'label'        => __( 'Date Time Picker', 'notification-plus' ),
				'desc'         => __( 'The Date Time Picker option type is tied to a standard form input field which displays a calendar pop-up that allow the user to pick any date and time when focus is given to the input field. The returned value is a date and time formatted string.', 'notification-plus' ),
				'std'          => '',
				'type'         => 'date-time-picker',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_dimension',
				'label'        => __( 'Dimension', 'notification-plus' ),
				'desc'         => __( 'The Dimension option type is used to set width and height values.', 'notification-plus' ),
				'std'          => '',
				'type'         => 'dimension',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_gallery',
				'label'        => __( 'Gallery', 'notification-plus' ),
				'desc'         => __( 'The Gallery option type saves a comma separated list of image attachment IDs. You will need to create a front-end function to display the images in your theme.', 'notification-plus' ),
				'std'          => '',
				'type'         => 'gallery',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_gallery_shortcode',
				'label'        => __( 'Gallery Shortcode', 'notification-plus' ),
				'desc'         => sprintf( __( 'The Gallery option type can also be saved as a shortcode by adding %s to the class attribute. Using the Gallery option type in this manner will result in a better user experience as you\'re able to save the link, column, and order settings.', 'notification-plus' ), '<code>prince-gallery-shortcode</code>' ),
				'std'          => '',
				'type'         => 'gallery',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => 'prince-gallery-shortcode',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_google_fonts',
				'label'        => __( 'Google Fonts', 'notification-plus' ),
				'desc'         => sprintf( __( 'The Google Fonts option type will dynamically enqueue any number of Google Web Fonts into the document %1$s. As well, once the option has been saved each font family will automatically be inserted into the %2$s array for the Typography option type. You can further modify the font stack by using the %3$s filter, which is passed the %4$s, %5$s, and %6$s parameters. The %6$s parameter is being passed from %7$s, so it will be the ID of a Typography option type. This will allow you to add additional web safe fonts to individual font families on an as-need basis.', 'notification-plus' ), '<code>HEAD</code>', '<code>font-family</code>', '<code>prince_google_font_stack</code>', '<code>$font_stack</code>', '<code>$family</code>', '<code>$field_id</code>', '<code>prince_recognized_font_families</code>' ),
				'std'          => array(
					array(
						'family'   => 'opensans',
						'variants' => array( '300', '300italic', 'regular', 'italic', '600', '600italic' ),
						'subsets'  => array( 'latin' ),
					),
				),
				'type'         => 'google-fonts',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_javascript',
				'label'        => __( 'JavaScript', 'notification-plus' ),
				'desc'         => '<p>' . sprintf( __( 'The JavaScript option type is a textarea that uses the %s code editor to highlight your JavaScript and display errors as you type.', 'notification-plus' ), '<code>ace.js</code>' ) . '</p>',
				'std'          => '',
				'type'         => 'javascript',
				'section'      => 'option_types',
				'rows'         => '20',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_link_color',
				'label'        => __( 'Link Color', 'notification-plus' ),
				'desc'         => __( 'The Link Color option type is used to set all link color states.', 'notification-plus' ),
				'std'          => '',
				'type'         => 'link-color',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_list_item',
				'label'        => __( 'List Item', 'notification-plus' ),
				'desc'         => __( 'The List Item option type allows for a great deal of customization. You can add settings to the List Item and those settings will be displayed to the user when they add a new List Item. Typical use is for creating sliding content or blocks of code for custom layouts.', 'notification-plus' ),
				'std'          => '',
				'type'         => 'list-item',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
				'settings'     => array(
					array(
						'id'           => 'demo_list_item_content',
						'label'        => __( 'Content', 'notification-plus' ),
						'desc'         => '',
						'std'          => '',
						'type'         => 'textarea-simple',
						'rows'         => '10',
						'post_type'    => '',
						'taxonomy'     => '',
						'min_max_step' => '',
						'class'        => '',
						'condition'    => '',
						'operator'     => 'and',
					),
				),
			),
			array(
				'id'           => 'demo_measurement',
				'label'        => __( 'Measurement', 'notification-plus' ),
				'desc'         => sprintf( __( 'The Measurement option type is a mix of input and select fields. The text input excepts a value and the select lets you choose the unit of measurement to add to that value. Currently the default units are %1$s, %2$s, %3$s, and %4$s. However, you can change them with the %5$s filter.', 'notification-plus' ), '<code>px</code>', '<code>%</code>', '<code>em</code>', '<code>pt</code>', '<code>prince_measurement_unit_types</code>' ),
				'std'          => '',
				'type'         => 'measurement',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_numeric_slider',
				'label'        => __( 'Numeric Slider', 'notification-plus' ),
				'desc'         => __( 'The Numeric Slider option type displays a jQuery UI slider. It will return a single numerical value for use in a custom function or loop.', 'notification-plus' ),
				'std'          => '',
				'type'         => 'numeric-slider',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '-500,5000,100',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_on_off',
				'label'        => __( 'On/Off', 'notification-plus' ),
				'desc'         => sprintf( __( 'The On/Off option type displays a simple switch that can be used to turn things on or off. The saved return value is either %1$s or %2$s.', 'notification-plus' ), '<code>on</code>', '<code>off</code>' ),
				'std'          => '',
				'type'         => 'on-off',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_page_checkbox',
				'label'        => __( 'Page Checkbox', 'notification-plus' ),
				'desc'         => __( 'The Page Checkbox option type displays a list of page IDs. It allows the user to check multiple page IDs for use in a custom function or loop.', 'notification-plus' ),
				'std'          => '',
				'type'         => 'page-checkbox',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_page_select',
				'label'        => __( 'Page Select', 'notification-plus' ),
				'desc'         => __( 'The Page Select option type displays a list of page IDs. It will return a single page ID for use in a custom function or loop.', 'notification-plus' ),
				'std'          => '',
				'type'         => 'page-select',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_post_checkbox',
				'label'        => __( 'Post Checkbox', 'notification-plus' ),
				'desc'         => __( 'The Post Checkbox option type displays a list of post IDs. It allows the user to check multiple post IDs for use in a custom function or loop.', 'notification-plus' ),
				'std'          => '',
				'type'         => 'post-checkbox',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_post_select',
				'label'        => __( 'Post Select', 'notification-plus' ),
				'desc'         => __( 'The Post Select option type displays a list of post IDs. It will return a single post ID for use in a custom function or loop.', 'notification-plus' ),
				'std'          => '',
				'type'         => 'post-select',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_radio',
				'label'        => __( 'Radio', 'notification-plus' ),
				'desc'         => __( 'The Radio option type displays a group of choices. It allows the user to choose one and will return that value as a string for use in a custom function or loop.', 'notification-plus' ),
				'std'          => '',
				'type'         => 'radio',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
				'choices'      => array(
					array(
						'value' => 'yes',
						'label' => __( 'Yes', 'notification-plus' ),
						'src'   => '',
					),
					array(
						'value' => 'no',
						'label' => __( 'No', 'notification-plus' ),
						'src'   => '',
					),
					array(
						'value' => 'maybe',
						'label' => __( 'Maybe', 'notification-plus' ),
						'src'   => '',
					),
				),
			),
			array(
				'id'           => 'demo_radio_image',
				'label'        => __( 'Radio Image', 'notification-plus' ),
				'desc'         => sprintf( __( 'the Radio Images option type is primarily used for layouts. However, you can filter the image list using %s. As well, you can add your own custom images using the choices array.', 'notification-plus' ), '<code>prince_radio_images</code>' ),
				'std'          => 'right-sidebar',
				'type'         => 'radio-image',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_select',
				'label'        => __( 'Select', 'notification-plus' ),
				'desc'         => __( 'The Select option type is used to list anything you want that would be chosen from a select list.', 'notification-plus' ),
				'std'          => '',
				'type'         => 'select',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
				'choices'      => array(
					array(
						'value' => '',
						'label' => __( '-- Choose One --', 'notification-plus' ),
						'src'   => '',
					),
					array(
						'value' => 'yes',
						'label' => __( 'Yes', 'notification-plus' ),
						'src'   => '',
					),
					array(
						'value' => 'no',
						'label' => __( 'No', 'notification-plus' ),
						'src'   => '',
					),
					array(
						'value' => 'maybe',
						'label' => __( 'Maybe', 'notification-plus' ),
						'src'   => '',
					),
				),
			),
			array(
				'id'           => 'demo_sidebar_select',
				'label'        => __( 'Sidebar Select', 'notification-plus' ),
				'desc'         => '<p>' . sprintf( __( 'This option type makes it possible for users to select a WordPress registered sidebar to use on a specific area. By using the two provided filters, %1$s, and %2$s we can be selective about which sidebars are available on a specific content area.', 'notification-plus' ), '<code>prince_recognized_sidebars</code>', '<code>prince_recognized_sidebars_{$field_id}</code>' ) . '</p><p>' . sprintf( __( 'For example, if we create a WordPress theme that provides the ability to change the Blog Sidebar and we don\'t want to have the footer sidebars available on this area, we can unset those sidebars either manually or by using a regular expression if we have a common name like %s.', 'notification-plus' ), '<code>footer-sidebar-$i</code>' ) . '</p>',
				'std'          => '',
				'type'         => 'sidebar-select',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_social_links',
				'label'        => __( 'Social Links', 'notification-plus' ),
				'desc'         => '<p>' . sprintf( __( 'The Social Links option type utilizes a drag & drop interface to create a list of social links. There are a few filters that make extending this option type easy. You can set the %1$s filter to %2$s and turn off loading default values. Use the %3$s filter to change the default values that are loaded. To filter the settings array use the %4$s filter.', 'notification-plus' ), '<code>prince_type_social_links_load_defaults</code>', '<code>false</code>', '<code>prince_type_social_links_defaults</code>', '<code>prince_social_links_settings</code>' ) . '</p>',
				'std'          => '',
				'type'         => 'social-links',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_spacing',
				'label'        => __( 'Spacing', 'notification-plus' ),
				'desc'         => __( 'The Spacing option type is used to set spacing values such as padding or margin in the form of top, right, bottom, and left.', 'notification-plus' ),
				'std'          => '',
				'type'         => 'spacing',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_tag_checkbox',
				'label'        => __( 'Tag Checkbox', 'notification-plus' ),
				'desc'         => __( 'The Tag Checkbox option type displays a list of tag IDs. It allows the user to check multiple tag IDs and will return that value as an array for use in a custom function or loop.', 'notification-plus' ),
				'std'          => '',
				'type'         => 'tag-checkbox',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_tag_select',
				'label'        => __( 'Tag Select', 'notification-plus' ),
				'desc'         => __( 'The Tag Select option type displays a list of tag IDs. It allows the user to select only one tag ID and will return that value for use in a custom function or loop.', 'notification-plus' ),
				'std'          => '',
				'type'         => 'tag-select',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_taxonomy_checkbox',
				'label'        => __( 'Taxonomy Checkbox', 'notification-plus' ),
				'desc'         => __( 'The Taxonomy Checkbox option type displays a list of taxonomy IDs. It allows the user to check multiple taxonomy IDs and will return that value as an array for use in a custom function or loop.', 'notification-plus' ),
				'std'          => '',
				'type'         => 'taxonomy-checkbox',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => 'category,post_tag',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_taxonomy_select',
				'label'        => __( 'Taxonomy Select', 'notification-plus' ),
				'desc'         => __( 'The Taxonomy Select option type displays a list of taxonomy IDs. It allows the user to select only one taxonomy ID and will return that value for use in a custom function or loop.', 'notification-plus' ),
				'std'          => '',
				'type'         => 'taxonomy-select',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => 'category,post_tag',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_text',
				'label'        => __( 'Text', 'notification-plus' ),
				'desc'         => __( 'The Text option type is used to save string values. For example, any optional or required text that is of reasonably short character length.', 'notification-plus' ),
				'std'          => '',
				'type'         => 'text',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_textarea',
				'label'        => __( 'Textarea', 'notification-plus' ),
				'desc'         => sprintf( __( 'The Textarea option type is a large string value used for custom code or text in the theme and has a WYSIWYG editor that can be filtered to change the how it is displayed. For example, you can filter %1$s, %2$s, %3$s, and %4$s.', 'notification-plus' ), '<code>wpautop</code>', '<code>media_buttons</code>', '<code>tinymce</code>', '<code>quicktags</code>' ),
				'std'          => '',
				'type'         => 'textarea',
				'section'      => 'option_types',
				'rows'         => '15',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_textarea_simple',
				'label'        => __( 'Textarea Simple', 'notification-plus' ),
				'desc'         => __( 'The Textarea Simple option type is a large string value used for custom code or text in the theme. The Textarea Simple does not have a WYSIWYG editor.', 'notification-plus' ),
				'std'          => '',
				'type'         => 'textarea-simple',
				'section'      => 'option_types',
				'rows'         => '10',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_textblock',
				'label'        => __( 'Textblock', 'notification-plus' ),
				'desc'         => __( 'The Textblock option type is used only on the Theme Option page. It will allow you to create & display HTML, but has no title above the text block. You can then use the Textblock to add a more detailed set of instruction on how the options are used in your theme. You would never use this in your themes template files as it does not save a value.', 'notification-plus' ),
				'std'          => '',
				'type'         => 'textblock',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_textblock_titled',
				'label'        => __( 'Textblock Titled', 'notification-plus' ),
				'desc'         => __( 'The Textblock Titled option type is used only on the Theme Option page. It will allow you to create & display HTML, and has a title above the text block. You can then use the Textblock Titled to add a more detailed set of instruction on how the options are used in your theme. You would never use this in your themes template files as it does not save a value.', 'notification-plus' ),
				'std'          => '',
				'type'         => 'textblock-titled',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_typography',
				'label'        => __( 'Typography', 'notification-plus' ),
				'desc'         => sprintf( __( 'The Typography option type is for adding typography styles to your theme either dynamically via the CSS option type above or manually with %1$s. The Typography option type has filters that allow you to remove fields or change the defaults. For example, you can filter %2$s to remove unwanted fields from all Background options or an individual one. You can also filter %3$s. These filters allow you to fine tune the select lists for your specific needs.', 'notification-plus' ), '<code>prince_get_option()</code>', '<code>prince_recognized_typography_fields</code>', '<code>prince_recognized_font_families</code>, <code>prince_recognized_font_sizes</code>, <code>prince_recognized_font_styles</code>, <code>prince_recognized_font_variants</code>, <code>prince_recognized_font_weights</code>, <code>prince_recognized_letter_spacing</code>, <code>prince_recognized_line_heights</code>, <code>prince_recognized_text_decorations</code> ' . __( 'and', 'notification-plus' ) . ' <code>prince_recognized_text_transformations</code>' ),
				'std'          => '',
				'type'         => 'typography',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_upload',
				'label'        => __( 'Upload', 'notification-plus' ),
				'desc'         => sprintf( __( 'The Upload option type is used to upload any WordPress supported media. After uploading, users are required to press the "%1$s" button in order to populate the input with the URI of that media. There is one caveat of this feature. If you import the Settings and have uploaded media on one site the old URI will not reflect the URI of your new site. You will have to re-upload or %2$s any media to your new server and change the URIs if necessary.', 'notification-plus' ), apply_filters( 'prince_upload_text', __( 'Done', 'notification-plus' ) ), 'FTP' ),
				'std'          => '',
				'type'         => 'upload',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => '',
				'condition'    => '',
				'operator'     => 'and',
			),
			array(
				'id'           => 'demo_upload_attachment_id',
				'label'        => __( 'Upload Attachment ID', 'notification-plus' ),
				'desc'         => sprintf( __( 'The Upload option type can also be saved as an attachment ID by adding %s to the class attribute.', 'notification-plus' ), '<code>prince-upload-attachment-id</code>' ),
				'std'          => '',
				'type'         => 'upload',
				'section'      => 'option_types',
				'rows'         => '',
				'post_type'    => '',
				'taxonomy'     => '',
				'min_max_step' => '',
				'class'        => 'prince-upload-attachment-id',
				'condition'    => '',
				'operator'     => 'and',
			),
		),
	);

	// Allow settings to be filtered before saving.
	$custom_settings = apply_filters( prince_settings_id() . '_args', $custom_settings );

	// Settings are not the same update the DB.
	if ( $saved_settings !== $custom_settings ) {
		update_option( prince_settings_id(), $custom_settings );
	}

	// Lets Prince know the UI Builder is being overridden.
	global $prince_has_custom_settings;
	$prince_has_custom_settings = true;
}
